apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller
  namespace: distributed-fractals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puller
  template:
    metadata:
      labels:
        app: puller
    spec:
      serviceAccountName: puller-sa
      containers:
        - name: puller
          image: martinfarres/python-puller_kubernetes-redis
          imagePullPolicy: Always
          env:
            - name: SERVER_HOST
              value: server
            - name: REDIS_HOST
              value: redis
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MPIPASS
              value: "mpi-password"
            - name: NODE_COUNT
              value: "4"
            - name: SLOTS_PER_NODE
              value: "2"
            - name: MPI_IMAGE
              value: "martinfarres/mpi-node:slim"
      # imagePullSecrets:
      #   - passuser: mpi-password
