apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller
  namespace: distributed-fractals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puller
  template:
    metadata:
      labels:
        app: puller
    spec:
      serviceAccountName: puller-sa  # Moved here
      containers:
        - name: puller
          image: martinfarres/python-puller_kubernetes-redis
          imagePullPolicy: Always  # Optional, helps during development
          env:
            - name: SERVER_HOST
              value: server
            - name: REDIS_HOST
              value: redis
            - name: POD_NAMESPACE  # Optional, if used in Python
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
