apiVersion: v1
kind: ServiceAccount
metadata:
  name: puller-sa
  namespace: distributed-fractals
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puller-role
  namespace: distributed-fractals
rules:
  # 1) Pods: to list & watch readiness
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # 2) Services: to create or detect headless Service
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "patch"]
  # 3) StatefulSets & scale subresource: to create or patch replicas
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puller-rb
  namespace: distributed-fractals
subjects:
  - kind: ServiceAccount
    name: puller-sa
roleRef:
  kind: Role
  name: puller-role
  apiGroup: rbac.authorization.k8s.io
