apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puller-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get","create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","create","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "create", "patch"]

