apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puller-rb
subjects:
  - kind: ServiceAccount
    name: puller-sa
roleRef:
  kind: Role
  name: puller-role
  apiGroup: rbac.authorization.k8s.io
