apiVersion: v1
kind: ServiceAccount
metadata:
  name: puller-sa
  namespace: distributed-fractals
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puller-role
  namespace: distributed-fractals
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puller-rb
  namespace: distributed-fractals
subjects:
  - kind: ServiceAccount
    name: puller-sa
roleRef:
  kind: Role
  name: puller-role
  apiGroup: rbac.authorization.k8s.io
