apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: puller-full-access
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "create", "patch"]
