apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: distributed-fractals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: martinfarres/python-server_kubernetes-redis
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
