apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: distributed-fractals
spec:
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
