apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: distributed-fractals
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
