apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-role
  namespace: autoscaler
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "namespaces", "services"]
    verbs: ["get", "list", "create", "patch", "delete"]
