apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-rolebinding
  namespace: distributed-fractals
subjects:
  - kind: ServiceAccount
    name: autoscaler-sa
    namespace: distributed-fractals
roleRef:
  kind: Role
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io
