kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: { name: autoscaler-crb }
subjects:
  - kind: ServiceAccount
    name: autoscaler-sa
    namespace: autoscaler
roleRef:
  kind: ClusterRole
  name: autoscaler-cr
  apiGroup: rbac.authorization.k8s.io
