apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-crb
subjects:
  - kind: ServiceAccount
    name: autoscaler-sa
    namespace: distributed-fractals
roleRef:
  kind: ClusterRole
  name: autoscaler-cr
  apiGroup: rbac.authorization.k8s.io
