apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis/redis-deployment.yaml
  - redis/redis-service.yaml
  - server/server-deployment.yaml
  - server/server-service.yaml
  - puller/puller-service-account.yaml
  - puller/puller-deployment.yaml
