apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis/redis-deployment.yaml
  - redis/redis-service.yaml
  - server/server-deployment.yaml
  - server/server-service.yaml
  - puller/puller-sa.yaml
  - puller/puller-role.yaml
  - puller/puller-rolebinding.yaml
  - puller/puller-clusterrole.yaml      
  - puller/puller-clusterrolebinding.yaml  
  - puller/puller-deployment.yaml
  - client/client-deployment.yaml
  - client/client-service.yaml

