apiVersion: v1
kind: Service
metadata:
  name: mpi-node
spec:
  clusterIP: None  # <-- Headless service
  selector:
    app: mpi-node
  ports:
    - port: 22
      name: ssh

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mpi-node
spec:
  serviceName: mpi-node
  replicas: 4  # You can modify this dynamically
  selector:
    matchLabels:
      app: mpi-node
  template:
    metadata:
      labels:
        app: mpi-node
    spec:
      containers:
        - name: mpi-node
          image: mpi-ssh-node  # Replace with actual image
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: shared-data
              mountPath: /home/mpiuser/app
      volumes:
        - name: shared-data
          emptyDir: {}  # Change to persistentVolumeClaim if needed
