apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: distributed-fractals
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cinder-sc-delete  # <- Reemplaza con el nombre de tu StorageClass si es distinto
