apiVersion: v1
kind: Service
metadata:
  name: client-backend
  namespace: distributed-fractals
spec:
  selector:
    app: client-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 30081
      targetPort: 30081
      nodePort: 30082  # puerto externo para el backend