apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-backend
  namespace: distributed-fractals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-backend
  template:
    metadata:
      labels:
        app: client-backend
    spec:
      containers:
        - name: client-backend
          image: martinfarres/client-backend-express
          ports:
            - containerPort: 30081  # puerto interno del contenedor Express