apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: distributed-fractals
spec:
  selector:
    app: client
  type: LoadBalancer
  loadBalancerIP: 10.66.100.200
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
